config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :games, only: [:index, :show, :new, :create] do
    member do
      get 'unity'
    end
    collection do
      post 'read_text'
    end
    collection do
      post 'load_game_object'
    end
  end
end

app/views/shared/_games.html.erb
<div class='game-content'>
  <%= link_to game_path(games, anchor: 'main') do %>
    <div class='game-container'>
      <div class='game-images'>
        <% unless games.stages[0].nil? %>
          <%# <%= image_tag games.stages[0].image.variant(resize: '200x200'), class: "stage-img" %>
        <% end %>
        <% unless games.game_objects[0].nil? %>
          <div class='player-img-container'>
            <%# <%= image_tag games.game_objects.where(player: true)[0].image.variant(resize: '200x200'), class: "player-img" %> %>
          </div>
        <% end %>
        <% unless games.game_objects[0].nil? %>
          <div class='object-img-container'>
            <%# <%= image_tag games.game_objects.where(object: true)[0].image.variant(resize: '200x200'), class: "object-img" %> %>
          </div>
        <% end %>
      </div>
      <div class='game-info'>
        <h3 class='game-name'>
          <%= games.name if games %>
        </h3>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class='header-content'>
  <div class='left'>
    <%= link_to root_path do%>
    <div class='logo'>
      ao<span class='logo-slash'>/</span>print 
    </div>
    <% end %>
    <div class='search-content'>
      <span>検索フォーム</span>
    </div>
  </div>
  <div class='right'> 
    <ul class='right-list'>
      <% if user_signed_in? %>
        <li class='user-icon'>
          <span><%= current_user.name %></span>
        </li>
        <li class='sign-out'>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :DELETE %>
        </li>
      <% else %>
        <li class='sign-in'>
          <%= link_to 'ログイン', new_user_session_path %>
        </li>
        <li class='sign-up'>
          <%= link_to 'ユーザー登録', new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_image.html.erb
<li class='image-groupe' id='image_groupe_<%= presetImage[:groupe][:column] %>'>
  <div class='groupe-name' id='groupe_name_<%= presetImage[:groupe][:column] %>'>
      <%= presetImage[:groupe][:index] %>
  </div>
  <div class='image-cards' id='image_cards_<%= presetImage[:groupe][:column] %>'>
  <% presetImage[:game_objects].each do |gameObject| %>
    <div class='image-card'>
      <%= image_tag gameObject.game_object.image.image, class: 'gameobject-image'%>
      <div class='image-name'></div>
      <div class='image-delete-button-wrapper'>
        <div class='image-delete-button'>x</div>
      </div>
    </div>
  <% end %>
  </div>
</li>

app/views/shared/_images.html.erb
<ul class='image-list' id='image_list'>
  <li class='image-groupe' id='uploaded_images'>
    <div class='groupe-name'>
      
    </div>
    <div class='image-cards' id='image_cards'>
      <div class='image-card' id='image_card'>
        <img src='#' class='image' id='image'>
        <div class='image-name' id='image_name'></div>
        <div class='image-delete-button-wrapper' id='image_delete_button_wrapper'>
          <div class='image-delete-button' id='image_delete_button'>x</div>
        </div>
      </div>
    </div>
  </li>
</ul>