config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :games, only: [:index, :show, :new, :create] do
    member do
      get 'unity'
    end
    collection do
      post 'read_text'
    end
    collection do
      post 'load_game_object'
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  
  with_options presence: true do
    validates :name
  end
  
  belongs_to :user
  has_many :game_objects
  has_many :stages
end

app/controllers/games_controller.rb
require 'base64'
require 'json'
require 'google/cloud/vision'

class GamesController < ApplicationController

  def index
    @image = Image.find_by(id: 154)
    groupe_names = [{column: 'upload', index: 'アップロード'},
                    {column: 'character', index: 'キャラクター'},
                    {column: 'stage', index: 'ステージ'},
                    {column: 'gimmick', index: 'ギミック'},
                    {column: 'background',index: '背景'},
                    {column: 'etc', index: 'その他'}]

    @games = Game.all.order(created_at: 'DESC')
    @gameForm = GameForm.new
    @presetImages = []
    groupe_names.each do |groupe_name|
      images = {groupe: groupe_name, game_objects: PresetGameObject.where(groupe: groupe_name[:column])}
      @presetImages.push(images)
    end
  end

  def load_game_object
    groupe_names = [{column: 'upload', index: 'アップロード'},
                    {column: 'character', index: 'キャラクター'},
                    {column: 'stage', index: 'ステージ'},
                    {column: 'gimmick', index: 'ギミック'},
                    {column: 'background',index: '背景'},
                    {column: 'etc', index: 'その他'}]

    data = []

    # 初回読み込み時の処理
    if params[:gameObject][:init]
      groupe_names.each do |name|
        game_objects = []
        PresetGameObject.where(groupe: name[:column]).limit(5).each do |preset_go|
          go = preset_go.game_object
          base64 = imageToBase64(go.images[0].image)
          type = image_type(base64)
          base64url = "data:image/" + type + ";base64," + base64
          image = {id: go.images[0].id, base64url: base64url}
          game_objects.push({symbol: go.symbol, position: {x: 0, y: 0, width: go.images[0].width, height: go.images[0].height, image: nil}, name: go.name, text: go.text, image: image, role: go.role_id, script: nil})
        end
        data.push({name: name, gameObjects: game_objects})
      end
    end

    render json: JSON.generate(data)
  end

  def show
    @game = Game.find_by(id: params[:id])
    @games = Game.all
  end

  def create
    game_form = GameForm.new(game_params)
    game_form.save
    redirect_to game_path(game_form.game)
  end

  def read_text
    # gcvテスト
    # image = @games.find_by(id: 1).stages[0].image
    image_annotator = Google::Cloud::Vision.image_annotator
    image_path = 'public/images/test.jpg'
    response = image_annotator.text_detection(
      image: {content: params[:url].replace('data:image/png;base64,', '')}
    )
    
    result = []
    response.responses.each do |res|
      res.text_annotations.each do |annotation|
        text = annotation.description
        vertices = Hash.new
        annotation.bounding_poly.vertices.each do |vertex|
          x = vertex.x
          y = vertex.y
          vertex = {x: x, y: y}
          vertices.merge!(vertex)
        end
        annotation = {text: text, vertices: vertices}
        result << annotation
      end
    end
    json = JSON.generate(result)
    render json: json
  end

  def unity
    game = Game.find_by(id: params[:id])
    stage = game.stages.first

    # Stageをhash化
    stage_size = {height: stage.height , width: stage.width}

    # Objectをhash化
    objects = []
    game.game_objects.each do |obj|
      # key名がupperCamelなのは、C#クラスとの互換のため
      puts obj
      object = {symbol: obj.symbol, image: imageToBase64(obj.images[0].image), meshData: obj.mesh_data}
      object[:role] = obj.role.id
      objects << object
    end

    # Positionをhash化
    positions = []
    stage.positions.each do |pos|
      positions << {symbol: pos.symbol, height: pos.height, width: pos.width, x: pos.x, y: pos.y}
    end

    # Object-Positionをhash化
    # TODO: 1object対多positionに対応する必要あり
    object_positions = []
    game.game_objects.each do |obj|
      objpos = obj.object_positions[0]
      # key名がupperCamelなのは、C#クラスとの互換のため
      object_positions << {objectId: game.game_objects.index{|obj| obj == GameObject.find_by(id: objpos.game_object_id)}, positionId: stage.positions.index{|pos| pos == Position.find_by(id: objpos.position_id)}}
    end

    # key名がupperCamelなのは、C#クラスとの互換のため
    hash = {stage: stage_size, objects: objects, positions: positions, objectPositions: object_positions}
    puts hash
    render json: hash
  end

  def game_params
    params.require(:game_form).permit(:name, :text, :objects, :canvas).merge(user_id: current_user.id)
  end

  def url_params
    params.permit(:url)
  end

  def imageToBase64(image)
    return Base64.encode64(image.download)
  end

  def image_type(base64)
    binary_data = Base64.decode64(base64)
    case binary_data
    when /GIF8[79]a/n
      return 'gif'
    when /\x89PNG/n
      return 'png'
    when /\xFF\xD8/n
      return 'jpeg'
    else
      raise "不明な形式の画像です。"
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<%= render 'shared/header' %>
<div class='main'>
  <div class='main-container'>
    <div class='introduce'>
    <img class='introduce-img' src='images/introduce.JPG'>
    </div>

    <%# games一覧 %>
    <div class='game-contents'>
      <%= render partial: 'shared/games', collection: @games %>
    </div>
    <%# games一覧 %>
    <div id='read-btn'>テストボタン</div>
    <div id='result'><%= @result %></div>
    <img style="max-width: 400px;"><input type="file" accept="image/*" />
    <div class='div1' id='div1'>
      parent
      <canvas class='child1' id='output'>child1</canvas>
      <%# <%= image_tag @image.image %> %>
      <div class='child2'>child2</div>
    </div>
  </div>
</div>

<%# games#new ボタン %>
<% if user_signed_in? %>
  <div class='create-btn' id='create_btn'>
    <span class='create-btn-text'>作る</span>
  </div>
<% end %>

<%# games#new モーダル %>
<div class='modal-parent' id='modal_parent'>
  <div class='modal-background' id='modal_background'></div>
  <div class='image-modal-background' id='image_modal_background'></div>
  
  <div class='image-modal'  id='image_modal'>
    <div class='image exit-btn' id='image_exit_btn'>×</div>
    <%# image list %>
    <div class='image-list-container' id='image_list_contaner'>
      <ul class='image-index' id='image_index'>
        <li class='index-card' id='uploaded'>
        アップロード
        </li>
        <li class='index-card' id='character_index'>
        キャラクター
        </li>
        <li class='index-card' id='stage_index'>
        ステージ
        </li>
        <li class='index-card' id='gimmick_index'>
        ギミック
        </li>
        <li class='index-card' id='back_ground_index'>
        背景
        </li>
        <li class='index-card' id='etc_index'>
        その他
        </li>
      </ul>
      <ul class='image-list' id='image_list'>
      </ul>
    </div>
    <div class='submit-line'>
      <div class='image submit-btn unclickable' id='image_submit_btn'>
        <div class='submit-text unclickable' id='submit_text_new'>決定</div>
        <div class='submit-text unclickable' id='submit_text_change'>変更</div>
      </div>  
    </div>
  </div>
  
  <div class='game-modal' id='game_modal'>
    <div class='modal-container'>

      <%# Game#newのフォーム %>
      <%= form_with model: @gameForm, id: 'game_form', url: games_path, class: 'game-form', local: true do |f| %>

      <%# png画像変換用のcanvas %>
      <canvas id='canvas' class='hidden'></canvas>

      <%# gui %>
      <div class='gui-container' id='gui_container'>
        <%# レイヤー設定 %>
        <div class='layer-container' id='layer_container'>
          <select class='layer-select' id='layer_select'>
            <option value="0">0</option>
          </select>
          <div class='add-layer-btn' id='add_layer_btn'>
          + レイヤー追加
          </div>
          <label class='inline-label'>
            <span class='label-name'>
            深さ : 
            </span>
            <input type='text' class='depth-input' id='depth'>
          </label>
        </div>
        <%# GUI %>
        <div class='preview-container' id='preview_container'>

          <%# object card %>
          <div class='object-info' id='object_info'>
            <ul class='setting-list'>
              <%# image %>
              <li class='setting-card'>
                <%# script側から作成するので本来は不要 %>
                <img src='https://1.bp.blogspot.com/-P4iXuEh6dZY/Wfg04oWG6eI/AAAAAAABH1I/S1sgOjG8b-QsAs_yp3Xv79tshwlJG6R8ACLcBGAs/s800/food_oden_chikuwabu.png' class='info-image' id='info_image'>
              </li>

              <%# 罫線 %>
              <div class="hr"></div>

              <%# position %>
              <li class='setting-card'>
                <ul class='positions' id='positions'>
                  <li>
                    <label class='inline-label'>
                      <span class='label-name position'>
                      X : 
                      </span>
                      <input type='text' class='position-input' id='x'>
                    </label>
                  </li>
                  <li>
                    <label class='inline-label'>
                      <span class='label-name position'>
                      Y :
                      </span>
                      <input type='text' class='position-input' id='y'>
                    </label>
                  </li>
                </ul>
              </li>
              <li class='setting-card'>
                <ul class='size' id='size'>
                  <li>
                    <label class='inline-label'>
                      <span class='label-name'>
                      横幅 :
                      </span>
                      <input type='text' class='position-input' id='width'>
                    </label>
                  </li>
                  <li>
                    <label class='inline-label'>
                      <span class='label-name'>
                      高さ :
                      </span>
                      <input type='text' class='position-input' id='height'>
                    </label>
                  </li>
                </ul>
              </li>

              <%# 罫線 %>
              <div class="hr"></div>

              <%# roleカラム %>
              <li class='setting-card script'>
                <p>役割</p>
                <div class='info-script-list'>
                <ul>
                  <li>
                    <select class='role-select' id='role_select' name="example">
                      <option value="1">ステージ</option>
                      <option value="2">プレイヤー</option>
                      <option value="3">敵</option>
                      <option value="4">アイテム</option>
                      <option value="5">ゴール</option>
                    </select>
                  </li>
                </ul>
              </div>
              </li>

            </ul>
          </div>

          <div class='add-object-btn' id='add_object_btn'>
            + 追加
          </div>
          <div class='hand-icon' id='hand_icon'>
            ✋
          </div>
        </div>
        <input type="range" name="zoom" id="zoom_range" value='100' min='1' max='200'> <input type='number' id='zoom_number' value='100'>
      </div>

      <%#= render 'shared/error_messages', model: @item %>

      <%# 非表示 %>
      <%# スクリプト編集モーダルの原型 %>
      <div class='script-modal hidden' id='scriptModal'>
        <div class='script-wrapper'>
          <div class='script-header'>
          <p>script editor</p>
          <select class='script-select' id='scriptSelect' name="example">
            <option value="object">ステージ</option>
            <option value="player">プレイヤー</option>
            <option value="enemy">敵キャラクター</option>
            <option value="item">アイテム</option>
            <option value="goal">ゴール</option>
          </select>
          </div>
          <div class='script-content'>
            <div class='script-list' id='scriptList'></div>
            <div class='script-field' id='scriptField'></div>
          </div>
        </div>
      </div>
      <%# 非表示 %>

      <%# 画像読み込みボタン %>
      <%# jsで画像リスト内に移動させる %>
      <label class='label hidden' id='image_input_label'>
        <p class='label-plus'>+</p>
        <%= f.file_field :image_input, class: 'hidden'%>
      </label>
      <%# 画像読み込みボタン %>

      
      <div id='textContainer'>
        <%= f.text_area :name, class:'name', placeholder:'ゲームのタイトル（40文字まで)', maxlength:'40' %>
        <%= f.text_area :text, class:'text', placeholder:'ゲームの説明' ,rows:'3' ,maxlength:'1000' %>
      </div>
      <pre></pre>
      <div class='submit-line'>
        <%= f.submit 'これで遊ぶ', class:'submit-btn', id:'submit_btn' %>
      </div>
      <% end %>
      <%# Game#newのフォーム %>

      <div class='exit-btn' id='exit_btn'>×</div>

    </div>
  </div>
</div>

app/views/games/show.html.erb
<%= render 'shared/header' %>
    <div class='main' id='main'>
      <div class='main-container'>
        <div class='game'>
          <div class="webgl-content">
            <div id="unityContainer"></div>
            <div class="footer">
              <div class="fullscreen" onclick="unityInstance.SetFullscreen(1)"></div>
              <div class='title'>
                <%= @game.name %>
              </div>
            </div>
          </div>
          <div class='user-name'>
            <%= @game.user.name %>
          </div>
          <div class='text' id='text'>
            <%= @game.text %>
          </div>
        </div>
        <div class='game-contents'>
          <%= render partial: 'shared/games', collection: @games %>
        </div>
      </div>
    </div>